### ISSUE TITLE
References for your script

### ISSUE THREAD

**Issue by Igort4** [wallacesam/deglitching#1]
Hello Wallace, I want to use your script in a Jupyter notebook, but I would like to mention this deglitch algorithm in a report, can you sent me some info on how to set the proper reference for your script?

**Comment by wallacesam** [comment]
Hi Igor!

[This paper](https://doi.org/10.1107/S1600577521003611) is the best citation for the algorithm:

Wallace, S. M., Alsina, M. A., & Gaillard, J. F. (2021). An algorithm for the automatic deglitching of X-ray absorption spectroscopy data. Journal of Synchrotron Radiation, 28(4).
